# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Adventures of a DevOps Consultant
email: jdthiele@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  This blog is where I share my thoughts, ideas, and lessons learned as I explore new
  technologies and how to use them to enable growth and efficiencies for organizations. I 
  hope to dive deeper into DevOps topics from the perspective of a Solaris and Linux sys 
  admin who is exploring the development world and cloud technologies. The opinions shared
  in this blog are my own and not my employer's.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jdthiele
github_username:  jdthiele
linkedin_username: davidthiele #from https://blog.r3bl.me/en/simple-social-media-links-jekyll/

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
permalink: /:year/:month/:day/:title.html

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
